### ISSUE TITLE
[Battlebird] Core Plugins

### ISSUE THREAD

**Issue by mortimr** [Horyus/battlebird#9]
All the logics will be inside the Core Plugins.

- [x] Determine all the tasks in the Battlebird Protocol
- [x] Determine all the plugins we need to make

---

On every plugin, list every:

- General Role
- Middleware
- Bush Method
- Exposed Method
- Exposed Classes
- Env Interaction
- Module Dependency
- Plugin Middleware Dependency
- Plugin Middleware After Dependency
- Plugin Middleware Before Dependency

---

- [x] [`btbd-crypto-plugin`](https://github.com/Horyus/etsedico/issues/20)
- [ ] [`btbd-recollection-plugin`](https://github.com/Horyus/etsedico/issues/21)
- [ ] [`btbd-handshake-plugin`](https://github.com/Horyus/etsedico/issues/22)
- [ ] [`btbd-key-exchange-plugin`](https://github.com/Horyus/etsedico/issues/23)
- [ ] [`btbd-timeout-plugin`](https://github.com/Horyus/etsedico/issues/24)
- [ ] [`btbd-connect-plugin`](https://github.com/Horyus/etsedico/issues/25)
- [ ] [`btbd-message-plugin`](https://github.com/Horyus/etsedico/issues/26)
- [ ] [`btbd-ping-plugin`](https://github.com/Horyus/etsedico/issues/27)
- [x] [`btbd-timestamp-plugin`](https://github.com/Horyus/etsedico/issues/28)
- [x] `btbd-crypto`
- [x] [`btbd-packets`](https://github.com/Horyus/etsedico/issues/29)
- [x] [`btbd-upackets`](https://github.com/Horyus/etsedico/issues/30)
- [ ] [`btbd-upackets-plugin`](https://github.com/Horyus/etsedico/issues/32)

---

**Comment by mortimr** [comment]
# Tasks

## Setup

- Load User Wallet

## Runtime

### Send

- Manage Raw Input
- Manage Raw Peer reference (use Eth addresses instead of Bush refs)
- Build Packet
- Cut Packet
- Send each Packet

### Receive

- Manage Recollection for non-parsable packets
- Manage clear certs exchange

**Comment by mortimr** [comment]
# Plugins

## esdc-packet-plugin

### Middlewares

#### pre_send

- build: Create packet from body given as argument. Switch everything to big endian. Encrypts to two Buffers: Header and Body.
- uPackets: create uPackets from Header and Body, and return multiple Buffers

#### receive

- rebuild: Takes encrypted Header and Body, decrypts, parse and return according instance

### Classes

- `Packet`
- `uPacket`

## esdc-timestamp-plugin

### Middleware

#### pre_send

- timestamp: Adds timestamp to payload.

## esdc-recon-plugin

### Middleware

#### receive

- sorter: Depending on header type, sorts packets. If no full packet, interrupt. If full, returns and recreate.

## esdc-crypto-plugin

### Config

- Inject crypto material in Env.

# Not Plugins

## esdc-crypto

### EC Functions

- encrypt: Buffer + Public Key => Buffer
- decrypt: Buffer + Private Key => Buffer
- sign: Buffer + Private Key => Buffer
- verify: Buffer + Public Key => boolean

### RSA Functions

- encrypt: Buffer + Shared RSA Key => Buffer
- decrypt: Buffer + Shared RSA Key => Buffer

**Comment by mortimr** [comment]
# User Actions

### send => Buffer + Address
### ping => Address
### connect => Address + IP + Port + PubKey?

**Comment by mortimr** [comment]
# Connection Status

The connection between two peers is defined by the two following diagrams (depending if the peer is the engager or the engaged)

- [Engager](https://github.com/Horyus/etsedico/blob/feature/ESDC-9.core-plugins/docs/umls/ConnectionStatusDiagram_Engager.png)
- [Engaged](https://github.com/Horyus/etsedico/blob/feature/ESDC-9.core-plugins/docs/umls/ConnectionStatusDiagram_Engaged.png)

**Comment by mortimr** [comment]
# User Actions

User Actions are actions created by the user, when using custom Bush methods.

The different User Actions are:

- [connect](https://github.com/Horyus/battlebird/blob/feature/ESDC-9.core-plugins/docs/system_operations/user_actions/UserActionConnect.png)
- [message](https://github.com/Horyus/battlebird/blob/feature/ESDC-9.core-plugins/docs/system_operations/user_actions/UserActionMessage.png)
- [ping](https://github.com/Horyus/battlebird/blob/feature/ESDC-9.core-plugins/docs/system_operations/user_actions/UserActionPing.png)
- [drop](https://github.com/Horyus/battlebird/blob/feature/ESDC-9.core-plugins/docs/system_operations/user_actions/UserActionDrop.png)
